server:
  port: 8000

spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false

  #配置 Jpa
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true

  redis:
    #数据库索引
    database: 1
    host: 192.168.38.34
    port: 6380
    password: fsscreport@123
    jedis:
      pool:
        #最大连接数
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 2000
        #最大空闲
        max-idle: 10
        #最小空闲
        min-idle: 8
    #连接超时时间
    timeout: 3000

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:cn/littleterry/modules/sys/mapper/xml/*Mapper.xml,classpath*:classpath*:cn/littleterry/mapper/xml/*Mapper.xml
  mybatis-plus.global-config.db-config.id-type : AUTO


# log打印sql
log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator

##logging
#logging:
#  level: warn

#七牛云
qiniu:
  # 文件大小 /M
  max-size: 15

#验证码有效时间/分钟
code:
  expiration: 5